### Indexing

In [1]:
import numpy as np
arr1=np.array([1,2,3,10,20,15])
print(arr1)
arr2=np.array([[23,89,90],[23,92,12],[23,14,90]])
print(arr2)
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

[ 1  2  3 10 20 15]
[[23 89 90]
 [23 92 12]
 [23 14 90]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [2]:
arr1#arr[index]

array([ 1,  2,  3, 10, 20, 15])

In [3]:
arr1[4]  # positive indexing  / forward indexing

20

In [5]:
arr1[-2]   # negative indexing  / bacjward indexing

20

In [6]:
# indexing for 2-D array
# arr2[row,coloumn]

arr2

array([[23, 89, 90],
       [23, 92, 12],
       [23, 14, 90]])

In [7]:
arr2[1,1]

92

In [8]:
arr2[0,2]

90

In [9]:
arr2[-1,-1]

90

In [10]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
# indexing for 3-D array

# arr3[layer,row,column]

arr3[0,1,1]

5

In [13]:
arr3[1,0,2]

9

### Slicing

In [19]:
#for 1D array its similar to normal indexing arr[start:stop:step]
print(arr1)
len(arr1)

[ 1  2  3 10 20 15]


6

In [20]:
print(arr1[:])
print(arr1[1:len(arr1)-1])

[ 1  2  3 10 20 15]
[ 2  3 10 20]


In [21]:
print(arr1[::2])   # (start:stop-1:step)

[ 1  3 20]


In [22]:
print(arr1[::3])

[ 1 10]


In [24]:
print(arr1[::1])

[ 1  2  3 10 20 15]


In [25]:
print(arr1[::-1])  # reverse order

[15 20 10  3  2  1]


In [26]:
print(arr1[::-2])

[15 10  2]


In [28]:
print(arr1[3:6])   # positive slicing
print(arr1[-3:-1])   # negative slicing

[10 20 15]
[10 20]


In [29]:
# slicing using 2D array

arr2

array([[23, 89, 90],
       [23, 92, 12],
       [23, 14, 90]])

In [30]:
# arr2[row,colomn]  ---> arr2[:,:]

In [31]:
arr2[1:3,1:3]

array([[92, 12],
       [14, 90]])

In [32]:
arr2

array([[23, 89, 90],
       [23, 92, 12],
       [23, 14, 90]])

In [34]:
arr2[0:3:2,1:]

array([[89, 90],
       [14, 90]])

In [38]:
arr2[0:3:2,:2]

array([[23, 89],
       [23, 14]])

In [39]:
#2D slicing[row->start:stop:step,column->start:stop:step]
arr2[1]

array([23, 92, 12])

In [40]:
# 3D slicing :

arr3#arr[layer->start:stop:end,row->start:stop:step,column->start:stop:step]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3[-1,-1,-1]

12

In [45]:
arr3[0,0:2,1:3]

array([[2, 3],
       [5, 6]])

In [48]:
arr4=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])

In [49]:
arr4

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [50]:
arr4.shape

(2, 2, 2, 3)